remote_theme: pmarsceill/just-the-docs

title: LiSPM
description: "Open-source Scanning Probe Microscope (STM/AFM)"

logo: "/assets/logo.svg"
favicon_ico: "/assets/favicon.ico"

# Navigation (adjust paths as needed)
nav:
  - Home: index.md
  - Parts: Parts/README.md

# Treat files in `docs/` as the site source when building
permalink: /:path/
